name: movies4u
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
##version: version name+version code
#version: 1.9.0+9
version: 2.0.0+11


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  provider: ^5.0.0
#  shimmer: ^1.1.2
  # scoped model
  scoped_model: ^1.1.0
  # dependency injection
  get_it: ^6.0.0
  carousel_slider: ^3.0.0
  cached_network_image: ^2.5.0
  flutter_rating_bar: ^4.0.0
  #  eva_icons_flutter: ^2.0.0
  flutter_staggered_grid_view: ^0.3.4
  flutter_tags: ^0.4.9
  youtube_player_flutter: ^7.0.0+7
  photo_view: ^0.11.1
  shared_preferences: ^2.0.5
#  font_awesome_flutter: ^8.8.1
  share: ^0.6.5+4
  in_app_update: ^2.0.0
  webview_flutter: ^1.0.7
  responsive_builder: ^0.3.0
  intl: ^0.17.0
  in_app_review: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Zillaslab
      fonts:
        - asset: assets/fonts/Zillaslab-bold.ttf
        - asset: assets/fonts/Zillaslab-light.ttf
        - asset: assets/fonts/Zillaslab-medium.ttf
        - asset: assets/fonts/Zillaslab-regular.ttf
    - family: PT
      fonts:
        - asset: assets/fonts/PT-bold.ttf
        - asset: assets/fonts/PT-italic.ttf
        - asset: assets/fonts/PT-regular.ttf
